### ISSUE TITLE
Application not starting in local 

### ISSUE THREAD

**Issue by gagandua078** [devondragon/SpringUserFramework#21]
Getting following error

![image](https://github.com/devondragon/SpringUserFramework/assets/39922405/e6464103-1a25-4797-bbdc-fafcba9fc98e)

**Comment by devondragon** [comment]
@gagandua078  just to confirm, is this on the main branch or branch https://github.com/devondragon/SpringUserFramework/tree/issue-19-OAuth_and_General_Improvements ?

**Comment by gagandua078** [comment]
Main branch is giving error, yeah I’ll test other branch as well

**Comment by gagandua078** [comment]
@devondragon Getting same error in all branches tried with mysql server, mariadb server in docker getting same error...

**Comment by devondragon** [comment]
Thank you for checking!  I'm sorry for the hassle.  I will look at this this weekend and hopefully have a fix for you ASAP!

**Comment by devondragon** [comment]
@gagandua078 This should be fixed in main.  Sorry about that!  Let me know if you have any questions or issues!
